"
" .vimrc
"
" Vim configuration resource file.  Specifies desired
" behavior for the vim editor.
"
:set tabstop=2     " Set the tabstop to 4 spaces
:set shiftwidth=2  " Shiftwidth should match tabstop
:set expandtab     " Convert tabs to <tabstop> number of spaces
:set nowrap        " Do not wrap lines longer than the window
:set nowrapscan    " Do not wrap while searching
:set backspace=2
:set number
:set ruler         " Show the cursor position all the time
:set showmatch     " Show matching () {} etc...
" Tell vim to remember certain things when we exit
"  '10  :  marks will be remembered for up to 10 previously edited files
"  "100 :  will save up to 100 lines for each register
"  :20  :  up to 20 lines of command-line history will be remembered
"  %    :  saves and restores the buffer list
"  n... :  where to save the viminfo files
set viminfo='10,\"100,:20,%,n~/.viminfo

" Switch syntax highlighting on, when the terminal has colors
if &t_Co > 2 || has("gui_running")
    :syntax on
    " Change the highlight color for Comment and Special
    " to Cyan.  Blue is too dark for a black background.
    :highlight Comment term=bold ctermfg=6  guifg=Cyan
    :highlight Special term=bold ctermfg=6  guifg=Cyan
endif

function! ResCur()
  if line("'\"") <= line("$")
    normal! g`"
    return 1
  endif
endfunction

augroup resCur
  autocmd!
  autocmd BufWinEnter * call ResCur()
augroup END
